http:
  enable: true
  trace: true
  host: 0.0.0.0
  port: 8080
  readHeaderTimeout: 30
  readTimeout: 60
  writeTimeout: 60
  idleTimeout: 300
  maxHeaderSize: "16kb"

framework:
  mode: release

cors:
  enabled: true
  allowedHeaders: [ "*" ]
  allowedMethods: [ "*" ]
  allowOrigins: [ "*" ]
  allowedDomains: [ ".*" ]
  exposeHeaders: [ ]
  allowCookies: false
  maxAge: 43200

log:
  callerDeep: 2
  level: debug
  noColor: false
  filePath: "logs/app.log_bak"
  maxSize: 10
  maxBackups: 6
  maxAge: 30
  compress: false

metrics:
  apiStatusEnable: true
  requestHistogram: true
  requestHistogramName: "http_request_duration_histogram"
  requestHistogramBucket: [ 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7 ]
  requestSummary: true
  requestSummaryName: "http_request_duration_summary"
  requestSummaryObjective: [ 0.5, 0.9, 0.99 ]
  requestTotal: true
  requestTotalName: "http_request_total"


otlp:
  enabled: true
  httpEndpoint: "127.0.0.1:4318"
  grpcEndpoint: "127.0.0.1:4317"
  insecure: true