application:
  appName: "case04"

log:
  level: debug

datasource:
  otlp: true
  host: "127.0.0.1"
  port: 3306
  database: "cases"
  username: "root"
  password: "redhat"
  debug: false
http:
  host: "127.0.0.1"
  port: 8080
  trace: true

otlp:
  grpcEndpoint: "10.54.44.78:4317"
  enableTLS: false